spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/usermanagement?serverTimezone=GMT%2b8
    username: root
    password: root
server:
  port: 9099
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  upload:
    path: C:/Users/YLY/Desktop/用户管理系统/存储文件/

